import type { League } from "@/types/leagues";

// Mock leagues data - فقط فوتسال و فوتبال ساحلی
// این داده‌ها صرفاً برای UI ادمین هستند و در آینده به API متصل می‌شوند.
export const mockLeagues: League[] = [
  {
    id: "league-1",
    title: "لیگ برتر فوتسال ایران",
    sportType: "futsal",
    competitionType: "league",
    season: "۱۴۰۳-۱۴۰۴",
    numberOfTeams: 14,
    promotionSpots: 0,
    relegationSpots: 2,
    hasGroups: false,
    hasStandingsTable: true,
    pointsSystem: {
      winPoints: 3,
      drawPoints: 1,
      lossPoints: 0,
    },
    status: "active",
    startDate: "1403-01-15",
    endDate: "1404-02-30",
    description: "رقابت‌های سطح اول فوتسال ایران با حضور ۱۴ تیم برتر کشور.",
    createdAt: "1403-01-01T10:00:00",
  },
  {
    id: "league-2",
    title: "لیگ برتر فوتبال ساحلی ایران",
    sportType: "beach_soccer",
    competitionType: "league",
    season: "۱۴۰۳",
    numberOfTeams: 10,
    promotionSpots: 0,
    relegationSpots: 1,
    hasGroups: false,
    hasStandingsTable: true,
    pointsSystem: {
      winPoints: 3,
      drawPoints: 1,
      lossPoints: 0,
    },
    status: "active",
    startDate: "1403-02-01",
    endDate: "1403-08-30",
    description: "لیگ حرفه‌ای فوتبال ساحلی با حضور برترین تیم‌های ایران.",
    createdAt: "1403-01-10T12:00:00",
  },
  {
    id: "league-3",
    title: "جام حذفی فوتسال ایران",
    sportType: "futsal",
    competitionType: "knockout",
    season: "۱۴۰۳",
    numberOfTeams: 32,
    twoLeggedMatches: false,
    hasThirdPlaceMatch: true,
    status: "draft",
    startDate: "1403-08-01",
    endDate: "1403-11-30",
    description: "جام حذفی فوتسال به صورت تک‌حذفی از مرحله یک‌شانزدهم نهایی.",
    createdAt: "1403-04-01T09:30:00",
  },
];
