import { Match, Competition, Season, MatchEvent, SportType, CompetitionType, MatchStatus } from "@/types/matches";

// Mock Competitions - Only Futsal and Beach Soccer
export const mockCompetitions: Competition[] = [
  // Futsal Competitions
  {
    id: "comp-1",
    name: "لیگ برتر فوتسال",
    sport: "futsal",
    type: "league",
    seasons: [
      {
        id: "season-1",
        name: "فصل ۱۴۰۳-۱۴۰۴",
        year: "۱۴۰۳-۱۴۰۴",
        startDate: "1403-07-01",
        endDate: "1404-06-30",
        isActive: true,
      },
    ],
  },
  {
    id: "comp-2",
    name: "جام حذفی فوتسال",
    sport: "futsal",
    type: "cup",
    seasons: [
      {
        id: "season-2",
        name: "فصل ۱۴۰۳",
        year: "۱۴۰۳",
        startDate: "1403-09-01",
        endDate: "1404-03-30",
        isActive: true,
      },
    ],
  },
  {
    id: "comp-3",
    name: "جام باشگاه‌های فوتسال",
    sport: "futsal",
    type: "cup",
    seasons: [
      {
        id: "season-3",
        name: "فصل ۱۴۰۳",
        year: "۱۴۰۳",
        startDate: "1403-08-01",
        endDate: "1404-02-28",
        isActive: true,
      },
    ],
  },
  // Beach Soccer Competitions
  {
    id: "comp-4",
    name: "لیگ فوتبال ساحلی",
    sport: "beach-soccer",
    type: "league",
    seasons: [
      {
        id: "season-4",
        name: "فصل ۱۴۰۳",
        year: "۱۴۰۳",
        startDate: "1403-06-01",
        endDate: "1403-09-30",
        isActive: true,
      },
    ],
  },
  {
    id: "comp-5",
    name: "جام بین‌المللی فوتبال ساحلی",
    sport: "beach-soccer",
    type: "international",
    seasons: [
      {
        id: "season-5",
        name: "فصل ۱۴۰۳",
        year: "۱۴۰۳",
        startDate: "1403-07-01",
        endDate: "1403-08-31",
        isActive: true,
      },
    ],
  },
];

// Mock Matches - Only Futsal and Beach Soccer
export const mockMatches: Match[] = [
  // Futsal Matches
  {
    id: "match-1",
    sport: "futsal",
    competitionId: "comp-1",
    competitionName: "لیگ برتر فوتسال",
    seasonId: "season-1",
    seasonName: "فصل ۱۴۰۳-۱۴۰۴",
    homeTeam: "گیتی پسند",
    homeTeamId: "team-1",
    awayTeam: "مس سونگون",
    awayTeamId: "team-2",
    homeScore: 3,
    awayScore: 1,
    status: "finished",
    date: "1403-09-15",
    time: "18:00",
    venue: "سالن آزادی",
    referee: "علی احمدی",
    attendance: 2500,
    events: [
      {
        id: "event-1",
        type: "goal",
        minute: 12,
        playerId: "player-1",
        playerName: "علی رضایی",
        team: "home",
        description: "گل",
      },
      {
        id: "event-2",
        type: "goal",
        minute: 25,
        playerId: "player-2",
        playerName: "مهدی جاوید",
        team: "home",
        description: "گل",
      },
      {
        id: "event-3",
        type: "blue-card",
        minute: 30,
        playerId: "player-3",
        playerName: "قدرت بهادری",
        team: "away",
        description: "کارت آبی (تعلیق موقت)",
      },
      {
        id: "event-4",
        type: "goal",
        minute: 38,
        playerId: "player-4",
        playerName: "احمد کریمی",
        team: "away",
        description: "گل",
      },
      {
        id: "event-5",
        type: "goal",
        minute: 45,
        playerId: "player-1",
        playerName: "علی رضایی",
        team: "home",
        description: "گل",
      },
      {
        id: "event-6",
        type: "timeout",
        minute: 15,
        playerId: "",
        playerName: "",
        team: "home",
        description: "وقفه درخواستی",
      },
    ],
    isPublished: true,
    createdAt: "1403-09-10T10:00:00",
    updatedAt: "1403-09-15T20:00:00",
  },
  {
    id: "match-2",
    sport: "futsal",
    competitionId: "comp-1",
    competitionName: "لیگ برتر فوتسال",
    seasonId: "season-1",
    seasonName: "فصل ۱۴۰۳-۱۴۰۴",
    homeTeam: "پالایش نفت",
    homeTeamId: "team-3",
    awayTeam: "سن‌ایچ ساوه",
    awayTeamId: "team-4",
    homeScore: null,
    awayScore: null,
    status: "scheduled",
    date: "1403-09-20",
    time: "19:30",
    venue: "سالن آزادی",
    events: [],
    isPublished: false,
    createdAt: "1403-09-10T10:00:00",
    updatedAt: "1403-09-10T10:00:00",
  },
  {
    id: "match-3",
    sport: "futsal",
    competitionId: "comp-2",
    competitionName: "جام حذفی فوتسال",
    seasonId: "season-2",
    seasonName: "فصل ۱۴۰۳",
    homeTeam: "ذوب آهن",
    homeTeamId: "team-5",
    awayTeam: "فولاد",
    awayTeamId: "team-6",
    homeScore: 4,
    awayScore: 2,
    status: "finished",
    date: "1403-09-18",
    time: "17:00",
    venue: "سالن شهید بهشتی",
    referee: "محمد رضایی",
    attendance: 1800,
    events: [
      {
        id: "event-7",
        type: "goal",
        minute: 5,
        playerId: "player-7",
        playerName: "حسین کریمی",
        team: "home",
        description: "گل",
      },
      {
        id: "event-8",
        type: "yellow-card",
        minute: 12,
        playerId: "player-8",
        playerName: "رضا احمدی",
        team: "away",
        description: "کارت زرد",
      },
      {
        id: "event-9",
        type: "goal",
        minute: 18,
        playerId: "player-9",
        playerName: "علی محمدی",
        team: "home",
        description: "گل",
      },
      {
        id: "event-10",
        type: "goal",
        minute: 25,
        playerId: "player-10",
        playerName: "مهدی حسینی",
        team: "away",
        description: "گل",
      },
      {
        id: "event-11",
        type: "substitution",
        minute: 30,
        playerId: "player-11",
        playerName: "احمد رضایی",
        team: "home",
        description: "تعویض",
      },
    ],
    isPublished: true,
    createdAt: "1403-09-15T10:00:00",
    updatedAt: "1403-09-18T19:00:00",
  },
  // Beach Soccer Matches
  {
    id: "match-4",
    sport: "beach-soccer",
    competitionId: "comp-4",
    competitionName: "لیگ فوتبال ساحلی",
    seasonId: "season-4",
    seasonName: "فصل ۱۴۰۳",
    homeTeam: "تیم ملی ایران",
    homeTeamId: "team-7",
    awayTeam: "تیم ملی برزیل",
    awayTeamId: "team-8",
    homeScore: 5,
    awayScore: 3,
    status: "finished",
    date: "1403-07-20",
    time: "17:00",
    venue: "ساحل کیش",
    referee: "احمد محمدی",
    attendance: 5000,
    events: [
      {
        id: "event-12",
        type: "goal",
        minute: 2,
        playerId: "player-12",
        playerName: "محمد رضایی",
        team: "home",
        description: "گل",
      },
      {
        id: "event-13",
        type: "goal",
        minute: 5,
        playerId: "player-13",
        playerName: "علی احمدی",
        team: "away",
        description: "گل",
      },
      {
        id: "event-14",
        type: "goal",
        minute: 8,
        playerId: "player-14",
        playerName: "حسین کریمی",
        team: "home",
        description: "گل",
      },
      {
        id: "event-15",
        type: "yellow-card",
        minute: 10,
        playerId: "player-15",
        playerName: "رضا محمدی",
        team: "away",
        description: "کارت زرد",
      },
    ],
    isPublished: true,
    createdAt: "1403-07-15T10:00:00",
    updatedAt: "1403-07-20T19:00:00",
  },
  {
    id: "match-5",
    sport: "beach-soccer",
    competitionId: "comp-5",
    competitionName: "جام بین‌المللی فوتبال ساحلی",
    seasonId: "season-5",
    seasonName: "فصل ۱۴۰۳",
    homeTeam: "تیم ملی ایران",
    homeTeamId: "team-9",
    awayTeam: "تیم ملی اسپانیا",
    awayTeamId: "team-10",
    homeScore: 6,
    awayScore: 4,
    status: "finished",
    date: "1403-07-25",
    time: "18:30",
    venue: "ساحل کیش",
    referee: "محمد حسینی",
    attendance: 6000,
    events: [
      {
        id: "event-16",
        type: "goal",
        minute: 1,
        playerId: "player-16",
        playerName: "علی رضایی",
        team: "home",
        description: "گل",
      },
      {
        id: "event-17",
        type: "goal",
        minute: 4,
        playerId: "player-17",
        playerName: "کارلوس سیلوا",
        team: "away",
        description: "گل",
      },
      {
        id: "event-18",
        type: "goal",
        minute: 7,
        playerId: "player-18",
        playerName: "مهدی جاوید",
        team: "home",
        description: "گل",
      },
      {
        id: "event-19",
        type: "red-card",
        minute: 9,
        playerId: "player-19",
        playerName: "خوان گارسیا",
        team: "away",
        description: "کارت قرمز",
      },
    ],
    isPublished: true,
    createdAt: "1403-07-20T10:00:00",
    updatedAt: "1403-07-25T20:00:00",
  },
  {
    id: "match-6",
    sport: "beach-soccer",
    competitionId: "comp-4",
    competitionName: "لیگ فوتبال ساحلی",
    seasonId: "season-4",
    seasonName: "فصل ۱۴۰۳",
    homeTeam: "تیم ملی پرتغال",
    homeTeamId: "team-11",
    awayTeam: "تیم ملی ایتالیا",
    awayTeamId: "team-12",
    homeScore: null,
    awayScore: null,
    status: "scheduled",
    date: "1403-08-05",
    time: "19:00",
    venue: "ساحل کیش",
    events: [],
    isPublished: false,
    createdAt: "1403-07-30T10:00:00",
    updatedAt: "1403-07-30T10:00:00",
  },
  // Additional Futsal matches for better standings calculation
  {
    id: "match-7",
    sport: "futsal",
    competitionId: "comp-1",
    competitionName: "لیگ برتر فوتسال",
    seasonId: "season-1",
    seasonName: "فصل ۱۴۰۳-۱۴۰۴",
    homeTeam: "گیتی پسند",
    homeTeamId: "team-1",
    awayTeam: "پالایش نفت",
    awayTeamId: "team-3",
    homeScore: 2,
    awayScore: 2,
    status: "finished",
    date: "1403-09-10",
    time: "18:00",
    venue: "سالن آزادی",
    referee: "علی احمدی",
    attendance: 2000,
    events: [],
    isPublished: true,
    createdAt: "1403-09-05T10:00:00",
    updatedAt: "1403-09-10T20:00:00",
  },
  {
    id: "match-8",
    sport: "futsal",
    competitionId: "comp-1",
    competitionName: "لیگ برتر فوتسال",
    seasonId: "season-1",
    seasonName: "فصل ۱۴۰۳-۱۴۰۴",
    homeTeam: "مس سونگون",
    homeTeamId: "team-2",
    awayTeam: "سن‌ایچ ساوه",
    awayTeamId: "team-4",
    homeScore: 4,
    awayScore: 1,
    status: "finished",
    date: "1403-09-12",
    time: "19:00",
    venue: "سالن آزادی",
    referee: "محمد رضایی",
    attendance: 2200,
    events: [],
    isPublished: true,
    createdAt: "1403-09-08T10:00:00",
    updatedAt: "1403-09-12T21:00:00",
  },
  {
    id: "match-9",
    sport: "futsal",
    competitionId: "comp-1",
    competitionName: "لیگ برتر فوتسال",
    seasonId: "season-1",
    seasonName: "فصل ۱۴۰۳-۱۴۰۴",
    homeTeam: "ذوب آهن",
    homeTeamId: "team-5",
    awayTeam: "گیتی پسند",
    awayTeamId: "team-1",
    homeScore: 1,
    awayScore: 3,
    status: "finished",
    date: "1403-09-14",
    time: "17:30",
    venue: "سالن شهید بهشتی",
    referee: "احمد کریمی",
    attendance: 1500,
    events: [],
    isPublished: true,
    createdAt: "1403-09-10T10:00:00",
    updatedAt: "1403-09-14T19:30:00",
  },
  // Additional Beach Soccer matches
  {
    id: "match-10",
    sport: "beach-soccer",
    competitionId: "comp-4",
    competitionName: "لیگ فوتبال ساحلی",
    seasonId: "season-4",
    seasonName: "فصل ۱۴۰۳",
    homeTeam: "تیم ملی برزیل",
    homeTeamId: "team-8",
    awayTeam: "تیم ملی اسپانیا",
    awayTeamId: "team-10",
    homeScore: 4,
    awayScore: 2,
    status: "finished",
    date: "1403-07-22",
    time: "18:00",
    venue: "ساحل کیش",
    referee: "احمد محمدی",
    attendance: 4500,
    events: [],
    isPublished: true,
    createdAt: "1403-07-18T10:00:00",
    updatedAt: "1403-07-22T20:00:00",
  },
];
